experiment:
  backend: pytorch
  data_config:
    strategy: fixed
    train_path: ../data/{0}/train.tsv
    validation_path: ../data/{0}/validation.tsv
    test_path: ../data/{0}/test.tsv
  dataset: allrecipes
  top_k: 20
  evaluation:
    cutoffs: [20]
    simple_metrics: [Recall, nDCG]
  gpu: 0
  external_models_path: ../external/models/__init__.py
  models:
    external.NGCF:
      meta:
        hyper_opt_alg: tpe
        hyper_max_evals: 20
        verbose: True
        save_weights: False
        validation_rate: 10
        validation_metric: Recall@20
        restore: False
        write_best_iterations: True
      lr: [loguniform, -9.21034037198, -5.29831736655]
      epochs: 400
      factors: 64
      batch_size: 128
      l_w: [loguniform, -11.512925465, 4.60517018599]
      n_layers: [choice, [1, 2, 3, 4]]
      weight_size: 64
      node_dropout: [loguniform, -2.30258509299, -0.22314355131]
      message_dropout: [loguniform, -2.30258509299, -0.22314355131]
      normalize: True
      seed: 42
      early_stopping:
        patience: 5
        mode: auto
        monitor: Recall@20
        verbose: True