experiment:
  backend: pytorch
  data_config:
    strategy: fixed
    train_path: ../data/{0}/train.tsv
    test_path: ../data/{0}/test.tsv
  dataset: yelp-2018
  top_k: 20
  evaluation:
    cutoffs: [20]
    simple_metrics: [Recall, nDCG]
  gpu: 0
  external_models_path: ../external/models/__init__.py
  models:
    external.SimGCL:
      meta:
        hyper_opt_alg: grid
        verbose: True
        save_weights: False
        validation_rate: 1
        validation_metric: Recall@20
        restore: False
      lr: 0.001
      epochs: 20
      factors: 64
      batch_size: 2048
      l_w: 1e-4
      n_layers: 3
      eps: 0.1
      reg_cl: 0.5
      seed: 42