experiment:
  backend: pytorch
  data_config:
    strategy: fixed
    train_path: ../data/{0}/train.tsv
    validation_path: ../data/{0}/validation.tsv
    test_path: ../data/{0}/test.tsv
  dataset: allrecipes
  top_k: 20
  evaluation:
    cutoffs: [20]
    simple_metrics: [Recall, nDCG]
  gpu: 0
  external_models_path: ../external/models/__init__.py
  models:
    external.UltraGCN:
      meta:
        hyper_opt_alg: tpe
        hyper_max_evals: 20
        verbose: True
        save_weights: False
        validation_rate: 5
        validation_metric: Recall@20
        restore: False
        write_best_iterations: True
      lr: 1e-4
      epochs: 2000
      factors: 64
      batch_size: 128
      g: 1e-4
      l: [loguniform, -2.30258509299, 1.2527629685]
      w1: [loguniform, -18.420680744, 0]
      w2: [loguniform, -18.420680744, 0]
      w3: [loguniform, -18.420680744, 0]
      w4: [loguniform, -18.420680744, 0]
      ii_n_n: 10
      n_n: 300
      n_w: 300
      s_s_p: False
      i_w: 1e-4
      seed: 42
      early_stopping:
        patience: 15
        mode: auto
        monitor: Recall@20
        verbose: True